### ISSUE TITLE
When will the octogibson dataset release?

### ISSUE THREAD

**Issue by xdhhh** [dongyh20/Octopus#1]
Thank you for your excellent work! I will appreciate it if you can tell  when the octogibson dataset will be released

**Comment by dongyh20** [comment]
Thanks for your attention of our work! We will release our OctoGibson training dataset as well as the instructions on how to use the collected data by the end of next week. We are working intensively to prepare for the dataset.

**Comment by Kira0096** [comment]
Hi, Thx for sharing! Any updates on the release?

**Comment by Kira0096** [comment]
> Thanks for your attention of our work! We will release our OctoGibson training dataset as well as the instructions on how to use the collected data by the end of next week. We are working intensively to prepare for the dataset.


Hi, Thx for sharing! Any updates on the release?

**Comment by Jingkang50** [comment]
Yes, we just released the dataset [here](https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/EmK_oqL6VoBBtjaERJD6P20BUt-CUtgJCcyGi1_Fo4bayw?e=JxKQOY)! Feel free to drop any question on anything!

**Comment by albertcity** [comment]
> Yes, we just released the dataset [here](https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/EmK_oqL6VoBBtjaERJD6P20BUt-CUtgJCcyGi1_Fo4bayw?e=JxKQOY)! Feel free to drop any question on anything!

I am interested in this dataset too. However, I found that the `main_reward` is all `0` in this dataset. Does this mean that the GPT4 actually is unable to make any reasonable plan?

**Comment by Weili-NLP** [comment]
> Yes, we just released the dataset [here](https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/EmK_oqL6VoBBtjaERJD6P20BUt-CUtgJCcyGi1_Fo4bayw?e=JxKQOY)! Feel free to drop any question on anything!

The dataset link appears to be broken. Are there any updated links available for the dataset?
![image](https://github.com/user-attachments/assets/55466d86-c96e-4d85-b1d6-c1851a751edd)

**Comment by choiszt** [comment]
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/a562f737-d67d-4d61-9817-39684bb20114">
Hi, Weili @Weili-NLP,
In my case, everything appears to be working correctly. Could you please check your VPN configuration or other connection settings?

Let me know if there is anything else I can assist with.
Best,

**Comment by Weili-NLP** [comment]
Thanks. The data link is available now.
