### ISSUE TITLE
How is the RLEF going specifically?

### ISSUE THREAD

**Issue by OrilinZ** [dongyh20/Octopus#8]
I'm curious about the RLEF process, and it's a pioneer work in embodied agents. Is the LLM run by simulation and tuned by RL simultaneously?

**Comment by dongyh20** [comment]
Thank you for expressing interest in our research. Our methodology primarily employs GPT-4 for the collection of training data, which we organize into a hierarchical tree structure. This structured dataset is then utilized to fine-tune VLMs. Subsequently, we conduct RLEF for efficiently and effectively finetuning. So the data collection(simulation) and RLEF don't happen simultaneously.
