### ISSUE TITLE
Is it possible to provide the configuration file that [task_path: "/PATH/TO/TASK/JSON"] points to?

### ISSUE THREAD

**Issue by elated-sawyer** [dongyh20/Octopus#9]
I would like to try this excellent method! Is it possible to provide the json file that `task_path: "/PATH/TO/TASK/JSON"` points to in the file `octogibson/config/process.yaml`? Thanks a lot!

![Screenshot from 2024-03-26 21-24-50](https://github.com/dongyh20/Octopus/assets/71584437/bdcb87b9-faaf-4b82-983f-739fb514c49d)

**Comment by choiszt** [comment]
Hi @elated-sawyer!
To load an OctoGibson scene and its corresponding BDDL task, you can use the `Octogibson.yaml` configuration file. In this file, you'll find a 'task' domain that specifies the BDDL task to be parsed by the OctoGibson environment.

The OctoGibson environment will automatically parse the BDDL task by searching for the corresponding JSON file within the BDDL files and load the inital states for the task.

By following this workflow, you can successfully load the OctoGibson scene and its associated BDDL task.

I hope this helps! Let me know if you have any further questions.

**Comment by elated-sawyer** [comment]
> Hi @elated-sawyer! We have uploaded a parsed json file of Octogibson task in `config` directory to load BDDL task in Octogibson Environment. I hope this helps! Let me know if you have any further questions.

Thank you very much for your prompt response, it is very helpful! 

Regarding the dataset, I have a question. My dataset was downloaded directly using the `python scripts/download_datasets.py` from OmniGibson (v1.0.0). However, it seems to be different from your dataset. For example, the running environment for the "assembling_gift_baskets" task in the json file provided by you is "Ihlen_0_int", but the dataset I downloaded shows that the running environment for this task is "Beechwood_0_garden". This causes the dataset I downloaded to be unable to run your tasks. 

Do you know why there is such a problem?

**Comment by elated-sawyer** [comment]
> > Hi @elated-sawyer! We have uploaded a parsed json file of Octogibson task in `config` directory to load BDDL task in Octogibson Environment. I hope this helps! Let me know if you have any further questions.
> 
> Thank you very much for your prompt response, it is very helpful!
> 
> Regarding the dataset, I have a question. My dataset was downloaded directly using the `python scripts/download_datasets.py` from OmniGibson (v1.0.0). However, it seems to be different from your dataset. For example, the running environment for the "assembling_gift_baskets" task in the json file provided by you is "Ihlen_0_int", but the dataset I downloaded shows that the running environment for this task is "Beechwood_0_garden". This causes the dataset I downloaded to be unable to run your tasks.
> 
> Do you know why there is such a problem?

I think I know where the problem lies. After downgrading OmniGibson to version 0.2.1, the dataset I downloaded is now consistent with the JSON files you provided. Thank you for your help! I will close this issue.
